export const destinations = [
  {
    id: "kyoto-japan",
    name: "Kyoto",
    country: "Japan",
    continent: "Asia",
    tagline: "Where ancient temples meet bamboo forests",
    description:
      "Kyoto is Japan's cultural capital — a city of 1,600 Buddhist temples, 400 Shinto shrines, and centuries of imperial history. Wander through Fushimi Inari's endless torii gates, meditate in Ryoan-ji's stone garden, or catch geisha hurrying through the narrow lanes of Gion at dusk. In spring, the city drowns in sakura blossoms; in autumn, maple leaves set the hillsides ablaze.",
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=600&q=80",
    bestTime: "March–May, Oct–Nov",
    budget: "$$",
    tags: ["Culture", "History", "Nature", "Food"],
    mustSee: ["Fushimi Inari Shrine", "Arashiyama Bamboo Grove", "Kinkaku-ji (Golden Pavilion)", "Gion District"],
    funFact: "Kyoto served as Japan's imperial capital for over 1,000 years before Tokyo.",
    emoji: "🏯",
    color: "#c1603a",
    visited: false,
  },
  {
    id: "patagonia-argentina",
    name: "Patagonia",
    country: "Argentina & Chile",
    continent: "South America",
    tagline: "Earth's edge — raw, wind-blasted, and impossibly beautiful",
    description:
      "Patagonia is the world's last great wilderness, where the Andes crash into the Southern Ocean in a riot of jagged peaks, turquoise lakes, and creaking glaciers. Trek the W Circuit in Torres del Paine, watch Perito Moreno calve car-sized blocks of ice into milky water, or drive the legendary Ruta 40 through miles of wind-swept steppe. It's big, cold, humbling, and unforgettable.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
    bestTime: "Nov–Feb",
    budget: "$$$",
    tags: ["Adventure", "Nature", "Hiking", "Wildlife"],
    mustSee: ["Torres del Paine", "Perito Moreno Glacier", "Los Glaciares NP", "Tierra del Fuego"],
    funFact: "The name 'Patagonia' may come from the word 'Patagón', used by Magellan to describe the indigenous Tehuelche people.",
    emoji: "🏔️",
    color: "#2b6cb0",
    visited: false,
  },
  {
    id: "marrakech-morocco",
    name: "Marrakech",
    country: "Morocco",
    continent: "Africa",
    tagline: "A sensory maze of color, spice, and ancient souks",
    description:
      "Marrakech is an assault on every sense in the best possible way. Lose yourself in the ancient medina's labyrinthine alleys, haggle for rugs and lanterns in the souks, and collapse into a rooftop riad as the call to prayer echoes over terracotta rooftops. Djemaa el-Fna square transforms from a daytime market into a magical carnival of storytellers, musicians, and sizzling street food after dark.",
    image: "https://images.unsplash.com/photo-1539020140153-e479b8621b3a?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1539020140153-e479b8621b3a?w=600&q=80",
    bestTime: "Mar–May, Sep–Nov",
    budget: "$$",
    tags: ["Culture", "Food", "Architecture", "Shopping"],
    mustSee: ["Djemaa el-Fna", "Bahia Palace", "Majorelle Garden", "Medina Souks"],
    funFact: "The medina of Marrakech is a UNESCO World Heritage Site and one of the largest car-free urban areas in the world.",
    emoji: "🕌",
    color: "#b89540",
    visited: false,
  },
  {
    id: "amalfi-italy",
    name: "Amalfi Coast",
    country: "Italy",
    continent: "Europe",
    tagline: "Cliffside villages dripping with lemons and la dolce vita",
    description:
      "The Amalfi Coast is Italy concentrated into 50 kilometres of vertigo-inducing beauty. Pastel-coloured villages cling to limestone cliffs above a sea of impossible blue, connected by hairpin roads and centuries-old footpaths. Eat fresh seafood in Positano, sip limoncello in Ravello, and swim in hidden grottos accessible only by boat. This is the Mediterranean dream in its purest form.",
    image: "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?w=600&q=80",
    bestTime: "May–Jun, Sep–Oct",
    budget: "$$$",
    tags: ["Scenic", "Food", "Romance", "Beach"],
    mustSee: ["Positano", "Ravello", "Path of the Gods", "Grotta dello Smeraldo"],
    funFact: "Amalfi was once a major maritime republic that rivalled Venice and Genoa in the 9th–11th centuries.",
    emoji: "🍋",
    color: "#7a9e7e",
    visited: false,
  },
  {
    id: "rajasthan-india",
    name: "Rajasthan",
    country: "India",
    continent: "Asia",
    tagline: "The land of maharajas, painted deserts, and living forts",
    description:
      "Rajasthan is India's most theatrical state — a royal landscape of amber forts, rose-pink cities, and vast stretches of Thar Desert dotted with camel caravans. Sleep in a converted palace in Udaipur, watch the sun set over the dunes in Jaisalmer, and get lost in the blue alleyways of Jodhpur. Every corner is a postcard, every meal a feast, and every local story a small epic.",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    bestTime: "Oct–Mar",
    budget: "$",
    tags: ["Culture", "History", "Desert", "Architecture"],
    mustSee: ["Amber Fort", "City Palace Udaipur", "Jaisalmer Fort", "Pushkar Camel Fair"],
    funFact: "Rajasthan contains five of India's six UNESCO World Heritage Sites related to hill forts.",
    emoji: "🏰",
    color: "#c1603a",
    visited: false,
  },
  {
    id: "iceland",
    name: "Iceland",
    country: "Iceland",
    continent: "Europe",
    tagline: "Fire and ice — nature at its most primal and theatrical",
    description:
      "Iceland is geology in real time. Watch geysers erupt on schedule, soak in hot springs under the Northern Lights, hike across black sand beaches to glacier lagoons filled with sculpted blue icebergs, and drive the Ring Road through a landscape that looks freshly made. In summer you can hike at midnight in full daylight; in winter the sky dances in emerald and violet.",
    image: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=600&q=80",
    bestTime: "Jun–Aug (midnight sun), Sep–Mar (Northern Lights)",
    budget: "$$$$",
    tags: ["Nature", "Adventure", "Northern Lights", "Unique"],
    mustSee: ["Northern Lights", "Jökulsárlón Glacier Lagoon", "Geysir", "Skógafoss"],
    funFact: "Iceland has no mosquitoes — the ecosystem simply never evolved to support them.",
    emoji: "🌋",
    color: "#2b6cb0",
    visited: false,
  },
];

export const getDestinationById = (id) =>
  destinations.find((d) => d.id === id) || null;
